/* eslint-disable */
    module.exports = {
  tracks: {
    'href': 'https://api.spotify.com/v1/search?query=ruby+red&type=track&market=US&offset=0&limit=5',
    'items': [{
      album: {
        album_type: 'single',
        artists: [{
          'external_urls': {
            'spotify': 'https://open.spotify.com/artist/1ybINI1qPiFbwDXamRtwxD',
          },
          'href': 'https://api.spotify.com/v1/artists/1ybINI1qPiFbwDXamRtwxD',
          'id': '1ybINI1qPiFbwDXamRtwxD',
          'name': 'Smino',
          'type': 'artist',
          uri: 'spotify:artist:1ybINI1qPiFbwDXamRtwxD',
        }],
        'available_markets': ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
        external_urls: {
          'spotify': 'https://open.spotify.com/album/5b3tupDh9sl0Mf9ZjR989N',
        },
        href: 'https://api.spotify.com/v1/albums/5b3tupDh9sl0Mf9ZjR989N',
        'id': '5b3tupDh9sl0Mf9ZjR989N',
        'images': [{
          'height': 640,
          'url': 'https://i.scdn.co/image/a5bfebeff0d8d5f32591d926b7ab4191c08c4762',
          width: 640,
        }, {
          'height': 300,
          'url': 'https://i.scdn.co/image/317ad1a38a98bd14a49191694d4029ebd4762374',
          'width': 300,
        }, {
          'height': 64,
          'url': 'https://i.scdn.co/image/6b8a8b9d0ce02c03e998a631088b4bd67e091399',
          width: 64,
        }],
        'name': 'S!ck S!ck S!ck',
        'release_date': '2016-12-01',
        release_date_precision: 'day',
        type: 'album',
        uri: 'spotify:album:5b3tupDh9sl0Mf9ZjR989N',
      },
      'artists': [{
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1ybINI1qPiFbwDXamRtwxD',
        },
        'href': 'https://api.spotify.com/v1/artists/1ybINI1qPiFbwDXamRtwxD',
        id: '1ybINI1qPiFbwDXamRtwxD',
        'name': 'Smino',
        type: 'artist',
        uri: 'spotify:artist:1ybINI1qPiFbwDXamRtwxD',
      }],
      'available_markets': ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
      disc_number: 1,
      duration_ms: 264125,
      explicit: true,
      external_ids: {
        'isrc': 'TCACU1628193',
      },
      external_urls: {
        'spotify': 'https://open.spotify.com/track/0E6GxVs1NLV9FxK9rK4K1G',
      },
      'href': 'https://api.spotify.com/v1/tracks/0E6GxVs1NLV9FxK9rK4K1G',
      id: '0E6GxVs1NLV9FxK9rK4K1G',
      is_local: false,
      name: 'Ruby Red',
      popularity: 55,
      preview_url: 'https://p.scdn.co/mp3-preview/709cbbdd6348e78de635c84dcef04e7c172e6417?cid=9eba74032ce24a46ad9fd2f07f064a55',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:0E6GxVs1NLV9FxK9rK4K1G',
    }, {
      'album': {
        'album_type': 'album',
        'artists': [{
          'external_urls': {
            'spotify': 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
          },
          href: 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
          'id': '1TUJBwovBrSV0NgaJ9cm5a',
          name: 'Suzanne Santo',
          'type': 'artist',
          uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
        }],
        'available_markets': ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
        'external_urls': {
          'spotify': 'https://open.spotify.com/album/7Bsz8Wc2xeIZVr0XC23Vfk',
        },
        'href': 'https://api.spotify.com/v1/albums/7Bsz8Wc2xeIZVr0XC23Vfk',
        'id': '7Bsz8Wc2xeIZVr0XC23Vfk',
        images: [{
          height: 640,
          'url': 'https://i.scdn.co/image/eda5260734457dca37d5c7675cdf31080bf5e92c',
          'width': 640,
        }, {
          'height': 300,
          url: 'https://i.scdn.co/image/62b2281692a796b6539fd11c8b7451e60bbfd041',
          width: 300,
        }, {
          height: 64,
          url: 'https://i.scdn.co/image/909cd5f7bb36002771a898dcad55cf456e8b6ae9',
          'width': 64,
        }],
        'name': 'Ruby Red',
        'release_date': '2017-08-11',
        'release_date_precision': 'day',
        'type': 'album',
        'uri': 'spotify:album:7Bsz8Wc2xeIZVr0XC23Vfk',
      },
      'artists': [{
        external_urls: {
          'spotify': 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
        },
        'href': 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
        id: '1TUJBwovBrSV0NgaJ9cm5a',
        'name': 'Suzanne Santo',
        type: 'artist',
        uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
      }],
      'available_markets': ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
      'disc_number': 1,
      'duration_ms': 281093,
      'explicit': true,
      'external_ids': {
        'isrc': 'TCADC1713000',
      },
      external_urls: {
        'spotify': 'https://open.spotify.com/track/76SsM4CODCKGNpCqtBovBb',
      },
      'href': 'https://api.spotify.com/v1/tracks/76SsM4CODCKGNpCqtBovBb',
      id: '76SsM4CODCKGNpCqtBovBb',
      'is_local': false,
      name: 'Ghost in My Bed',
      'popularity': 30,
      'preview_url': 'https://p.scdn.co/mp3-preview/292b974fad8fd0410ef36c18d2783f9adf246e57?cid=9eba74032ce24a46ad9fd2f07f064a55',
      'track_number': 2,
      type: 'track',
      uri: 'spotify:track:76SsM4CODCKGNpCqtBovBb',
    }, {
      'album': {
        'album_type': 'album',
        artists: [{
          'external_urls': {
            'spotify': 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
          },
          'href': 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
          'id': '1TUJBwovBrSV0NgaJ9cm5a',
          name: 'Suzanne Santo',
          'type': 'artist',
          uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
        }],
        available_markets: ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
        'external_urls': {
          spotify: 'https://open.spotify.com/album/7Bsz8Wc2xeIZVr0XC23Vfk',
        },
        'href': 'https://api.spotify.com/v1/albums/7Bsz8Wc2xeIZVr0XC23Vfk',
        id: '7Bsz8Wc2xeIZVr0XC23Vfk',
        'images': [{
          height: 640,
          'url': 'https://i.scdn.co/image/eda5260734457dca37d5c7675cdf31080bf5e92c',
          width: 640,
        }, {
          height: 300,
          url: 'https://i.scdn.co/image/62b2281692a796b6539fd11c8b7451e60bbfd041',
          width: 300,
        }, {
          height: 64,
          'url': 'https://i.scdn.co/image/909cd5f7bb36002771a898dcad55cf456e8b6ae9',
          width: 64,
        }],
        'name': 'Ruby Red',
        release_date: '2017-08-11',
        'release_date_precision': 'day',
        type: 'album',
        'uri': 'spotify:album:7Bsz8Wc2xeIZVr0XC23Vfk',
      },
      'artists': [{
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
        },
        href: 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
        id: '1TUJBwovBrSV0NgaJ9cm5a',
        'name': 'Suzanne Santo',
        type: 'artist',
        uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
      }, {
        'external_urls': {
          spotify: 'https://open.spotify.com/artist/7qKoy46vPnmIxKCN6ewBG4',
        },
        href: 'https://api.spotify.com/v1/artists/7qKoy46vPnmIxKCN6ewBG4',
        id: '7qKoy46vPnmIxKCN6ewBG4',
        name: 'Butch Walker',
        type: 'artist',
        uri: 'spotify:artist:7qKoy46vPnmIxKCN6ewBG4',
      }],
      available_markets: ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
      disc_number: 1,
      'duration_ms': 278293,
      explicit: false,
      'external_ids': {
        'isrc': 'QM6MZ1782489',
      },
      'external_urls': {
        'spotify': 'https://open.spotify.com/track/43EJA8UNhZCUuo7RpQX9Nw',
      },
      'href': 'https://api.spotify.com/v1/tracks/43EJA8UNhZCUuo7RpQX9Nw',
      id: '43EJA8UNhZCUuo7RpQX9Nw',
      'is_local': false,
      name: 'Better Than That',
      popularity: 26,
      preview_url: 'https://p.scdn.co/mp3-preview/bf9848e39edc876c95fbc4cae9743349e7c44c52?cid=9eba74032ce24a46ad9fd2f07f064a55',
      track_number: 10,
      type: 'track',
      'uri': 'spotify:track:43EJA8UNhZCUuo7RpQX9Nw',
    }, {
      album: {
        'album_type': 'album',
        'artists': [{
          'external_urls': {
            spotify: 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
          },
          href: 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
          'id': '1TUJBwovBrSV0NgaJ9cm5a',
          'name': 'Suzanne Santo',
          'type': 'artist',
          uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
        }],
        'available_markets': ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
        'external_urls': {
          spotify: 'https://open.spotify.com/album/7Bsz8Wc2xeIZVr0XC23Vfk',
        },
        'href': 'https://api.spotify.com/v1/albums/7Bsz8Wc2xeIZVr0XC23Vfk',
        id: '7Bsz8Wc2xeIZVr0XC23Vfk',
        images: [{
          height: 640,
          url: 'https://i.scdn.co/image/eda5260734457dca37d5c7675cdf31080bf5e92c',
          'width': 640,
        }, {
          height: 300,
          url: 'https://i.scdn.co/image/62b2281692a796b6539fd11c8b7451e60bbfd041',
          width: 300,
        }, {
          'height': 64,
          'url': 'https://i.scdn.co/image/909cd5f7bb36002771a898dcad55cf456e8b6ae9',
          'width': 64,
        }],
        'name': 'Ruby Red',
        'release_date': '2017-08-11',
        'release_date_precision': 'day',
        type: 'album',
        'uri': 'spotify:album:7Bsz8Wc2xeIZVr0XC23Vfk',
      },
      'artists': [{
        external_urls: {
          'spotify': 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
        },
        href: 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
        'id': '1TUJBwovBrSV0NgaJ9cm5a',
        'name': 'Suzanne Santo',
        type: 'artist',
        'uri': 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
      }],
      available_markets: ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
      'disc_number': 1,
      duration_ms: 228906,
      'explicit': false,
      'external_ids': {
        isrc: 'QM6MZ1782480',
      },
      'external_urls': {
        'spotify': 'https://open.spotify.com/track/2j3wG4efBRMSHR0GZ9g8tk',
      },
      'href': 'https://api.spotify.com/v1/tracks/2j3wG4efBRMSHR0GZ9g8tk',
      id: '2j3wG4efBRMSHR0GZ9g8tk',
      'is_local': false,
      name: 'Handshake',
      popularity: 24,
      preview_url: 'https://p.scdn.co/mp3-preview/9fd44b7a88d67b61df3c70c0dd7dd5ec0af073e5?cid=9eba74032ce24a46ad9fd2f07f064a55',
      track_number: 1,
      type: 'track',
      'uri': 'spotify:track:2j3wG4efBRMSHR0GZ9g8tk',
    }, {
      'album': {
        album_type: 'album',
        artists: [{
          external_urls: {
            'spotify': 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
          },
          'href': 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
          id: '1TUJBwovBrSV0NgaJ9cm5a',
          'name': 'Suzanne Santo',
          type: 'artist',
          'uri': 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
        }],
        available_markets: ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
        'external_urls': {
          'spotify': 'https://open.spotify.com/album/7Bsz8Wc2xeIZVr0XC23Vfk',
        },
        'href': 'https://api.spotify.com/v1/albums/7Bsz8Wc2xeIZVr0XC23Vfk',
        id: '7Bsz8Wc2xeIZVr0XC23Vfk',
        images: [{
          'height': 640,
          'url': 'https://i.scdn.co/image/eda5260734457dca37d5c7675cdf31080bf5e92c',
          width: 640,
        }, {
          height: 300,
          'url': 'https://i.scdn.co/image/62b2281692a796b6539fd11c8b7451e60bbfd041',
          width: 300,
        }, {
          'height': 64,
          url: 'https://i.scdn.co/image/909cd5f7bb36002771a898dcad55cf456e8b6ae9',
          width: 64,
        }],
        'name': 'Ruby Red',
        release_date: '2017-08-11',
        release_date_precision: 'day',
        'type': 'album',
        uri: 'spotify:album:7Bsz8Wc2xeIZVr0XC23Vfk',
      },
      'artists': [{
        'external_urls': {
          spotify: 'https://open.spotify.com/artist/1TUJBwovBrSV0NgaJ9cm5a',
        },
        'href': 'https://api.spotify.com/v1/artists/1TUJBwovBrSV0NgaJ9cm5a',
        id: '1TUJBwovBrSV0NgaJ9cm5a',
        name: 'Suzanne Santo',
        type: 'artist',
        uri: 'spotify:artist:1TUJBwovBrSV0NgaJ9cm5a',
      }],
      available_markets: ['AD', 'AR', 'AT', 'AU', 'BE', 'BG', 'BO', 'BR', 'CA', 'CH', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HN', 'HU', 'ID', 'IE', 'IL', 'IS', 'IT', 'JP', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'MX', 'MY', 'NI', 'NL', 'NO', 'NZ', 'PA', 'PE', 'PH', 'PL', 'PT', 'PY', 'RO', 'SE', 'SG', 'SK', 'SV', 'TH', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA'],
      'disc_number': 1,
      duration_ms: 222706,
      explicit: false,
      'external_ids': {
        isrc: 'QM6MZ1782483',
      },
      external_urls: {
        'spotify': 'https://open.spotify.com/track/7p3i2XiuDDCmizONXkztSq',
      },
      href: 'https://api.spotify.com/v1/tracks/7p3i2XiuDDCmizONXkztSq',
      id: '7p3i2XiuDDCmizONXkztSq',
      is_local: false,
      name: 'Best out of Me',
      popularity: 23,
      'preview_url': 'https://p.scdn.co/mp3-preview/4889d4d529bc934e722ce970873135867c5ab6e9?cid=9eba74032ce24a46ad9fd2f07f064a55',
      track_number: 4,
      'type': 'track',
      'uri': 'spotify:track:7p3i2XiuDDCmizONXkztSq',
    }],
    limit: 5,
    'next': 'https://api.spotify.com/v1/search?query=ruby+red&type=track&market=US&offset=5&limit=5',
    'offset': 0,
    'previous': null,
    'total': 542,
  },
};
/* eslint-enable */
